### ISSUE TITLE
RogueM/PanTiltFacetracker branch

### ISSUE THREAD

**Issue by TCIII** [pimoroni/PanTiltFacetracker#6]
There appears to be no way to submit an issue on the RogueM/PanTiltFacetracker branch. Therefore I am posting here in the Master branch.
Would it be possible for RogueM to update his PanTiltFacetracker branch as the Adafruit-gpio is now obsolete and would it be possible to add PID code to improve the gimbal movement as seen here in this Pan/tilt face tracking project: https://www.pyimagesearch.com/2019/04/01/pan-tilt-face-tracking-with-a-raspberry-pi-and-opencv/
I will be glad to integrate and test any code changes as soon as they become available.
Regards,
TCIII

**Comment by Gadgetoid** [comment]
Rogue hasn't worked for us in some time (😢) since he was launching a card game among other committments. If you want to make your own fork and submit these changes you're more than welcome!

I have a suspicion that most of this code is old/broken/non-functional since, IIRC, the OpenCV API likes to change frequently.

**Comment by TCIII** [comment]
Thanks for the update, much appreciated.
I am only a beginner when it comes to Python coding, but I do well with C++.
I guess that I will close this issue as the code is too old to bother with.
